# Generated by Django 6.0.7 on 2026-10-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Quiénes Somos', max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('descripcion', models.TextField()),
                ('mision', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('historia', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='nosotros/')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nosotros',
                'verbose_name_plural': 'Nosotros',
            },
        ),
    ]
