# Generated by Django 6.0.7 on 2026-10-05 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_nosotros'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alto en cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ancho en cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='colores_disponibles',
            field=models.CharField(blank=True, help_text='Colores separados por comas', max_length=300),
        ),
        migrations.AddField(
            model_name='producto',
            name='materiales',
            field=models.TextField(blank=True, help_text='Materiales de elaboración'),
        ),
        migrations.AddField(
            model_name='producto',
            name='opciones_personalizacion',
            field=models.TextField(blank=True, help_text='Opciones de personalización'),
        ),
        migrations.AddField(
            model_name='producto',
            name='personalizable',
            field=models.BooleanField(default=False, help_text='¿Se puede personalizar?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='profundidad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profundidad en cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiempo_elaboracion',
            field=models.CharField(blank=True, help_text='Ej: 3-5 días hábiles', max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'ordering': ['orden'],
            },
        ),
    ]
