# Generated by Django 6.0.7 on 2026-10-05 04:19

import catalogo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_producto_alto_producto_ancho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[catalogo.validators.validar_precio_positivo]),
        ),
    ]
