# Generated by Django 6.0.7 on 2026-10-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiempo_entrega',
            field=models.CharField(blank=True, help_text='Ej: 3-5 días hábiles', max_length=100),
        ),
    ]
