# Generated by Django 6.0.7 on 2026-10-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_producto_tiempo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.ImageField(blank=True, help_text='Imagen PNG sin fondo (máx. 100x100 sugerido)', null=True, upload_to='categorias/'),
        ),
    ]
