# Generated by Django 6.0.7 on 2026-10-04 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('fecha_evento', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('confirmado', 'Confirmado'), ('preparacion', 'En preparación'), ('entregado', 'Entregado/Cerrado'), ('cancelado', 'Cancelado')], default='nuevo', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
            },
        ),
    ]
