# Generated by Django 6.0.7 on 2026-10-05 04:19

import catalogo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente_telefono',
            field=models.CharField(max_length=20, validators=[catalogo.validators.validar_telefono_mexicano]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_evento',
            field=models.DateField(validators=[catalogo.validators.validar_fecha_futura]),
        ),
    ]
